[project]
name = "suppotflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "email-validator>=2.3.0",
    "fastapi>=0.141.1",
    "llama-index>=0.14.25",
    "llama-index-embeddings-huggingface>=0.8.0",
    "llama-index-embeddings-openai>=0.6.0",
    "llama-index-llms-groq>=0.6.1",
    "llama-index-llms-openai>=0.7.10",
    "llama-index-vector-stores-pinecone>=0.9.0",
    "mysql-connector-python>=26.7.0",
    "pinecone>=9.1.0",
    "pydantic>=2.13.5",
    "pyjwt>=2.12,<3",
    "pymysql>=1.2.0",
    "python-dotenv>=1.2.3",
    "python-multipart>=0.0.22,<1",
    "sentence-transformers>=6.1.0",
    "sqlacodegen>=4.0.4",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.52.4",
]
